### ISSUE TITLE
Unit Test Features

### ISSUE THREAD

**Issue by avroshk** [avroshk/7100ProjectSource#2]
[Unit Testing of Features.docx](https://github.com/avroshk/7100ProjectSource/files/42521/Unit.Testing.of.Features.docx)
Some features like Spectral Flux and Roll Off are returning different values compared to the results generated in matlab.
Tasks:
1) Make sure we are using the same window function 
2) Write code to read audio from file instead to live audio
3) Compare block by block

**Comment by avroshk** [comment]
All features have been successfully unit-tested. Results attached in the document.
The test was done using a 31seconds long stereo sample.

1) Testing: Used sndfile.h to read audio file into audio buffers

2) Spectral Flux and Roll Off results different from matlab
Root cause: Input was normalized block by block which was a bad idea.

3) Pitch Chroma optimization
Fix: Optimized my pitch chroma code by creating weighting filter. 

4) Handled interleaved stereo input

[Unit Testing of Features.docx](https://github.com/avroshk/7100ProjectSource/files/43476/Unit.Testing.of.Features.docx)

**Comment by alexanderlerch** [comment]
Very good. Just a note on your use of the term unit test: that is usually a suite of tests available for validation at all times; they are part of your project and reproducible. Implementing a command line for debugging is good practice, but I wouldn't refer to it as unit test.

**Comment by avroshk** [comment]
Thanks for pointing that out Alex. I used the term unit-test here in the context of basic building blocks of my code that is the feature extraction. It's will be a good idea to move my 'read audio-file' code into an easily executable command line and make it reusable.
